### PR TITLE
module 'esphome.components.binary_sensor' has no attribute '_UNDEF'

### PR DESCRIPTION
**Pull request by bligeti**
This pull request is fixing the same issue as the other pending pull request #3, but this one is copying the 'official' updates applied on the origninal esphome opentherm library:
 [esphome #8725](https://github.com/esphome/esphome/pull/8725)
 [esphome #8756](https://github.com/esphome/esphome/pull/8756)

### CODE REVIEW

**Comment by diyless** [comment]
@bligeti is it actual? does it work with the latest ESPHome updates? we've seen you mentioned this PR in other [issue](https://github.com/diyless/esphome-opentherm-t3/issues/5)

**Comment by bligeti** [comment]
Now it is working with ESPHome 2025.8.2 and IDF 5.4.2. Applied a workaround for the UART regression which was mentioned in the issue.
